BEGIN TRANSACTION;

-- DROP TABLE IF EXISTS BEAR_CONTEXT;
-- DROP TABLE IF EXISTS PAPA_BEAR;
-- DROP TABLE IF EXISTS MAMA_BEAR;
-- DROP TABLE IF EXISTS BABY_BEAR;
-- DROP TABLE IF EXISTS BEAR_TOY;
-- DROP TABLE IF EXISTS DEER_FRIEND;
--
-- CREATE TABLE BEAR_CONTEXT
-- (
--   BEAR_CONTEXT_ID INT NOT NULL,
--
--   PRIMARY KEY (BEAR_CONTEXT_ID)
-- );
--
-- CREATE TABLE PAPA_BEAR
-- (
--   BEAR_CONTEXT_ID INT NOT NULL,
--   PAPA_BEAR_ID    INT NOT NULL,
--   NAME            VARCHAR(200),
--
--   PRIMARY KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID),
--   FOREIGN KEY (BEAR_CONTEXT_ID) REFERENCES BEAR_CONTEXT (BEAR_CONTEXT_ID)
-- );
--
-- CREATE TABLE MAMA_BEAR
-- (
--   BEAR_CONTEXT_ID INT NOT NULL,
--   PAPA_BEAR_ID    INT NOT NULL,
--   MAMA_BEAR_ID    INT NOT NULL,
--   NAME            VARCHAR(200),
--
--   PRIMARY KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID),
--   FOREIGN KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID) REFERENCES PAPA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID)
-- );
--
-- CREATE TABLE BABY_BEAR
-- (
--   BEAR_CONTEXT_ID INT NOT NULL,
--   PAPA_BEAR_ID    INT NOT NULL,
--   MAMA_BEAR_ID    INT NOT NULL,
--   BABY_BEAR_ID    INT NOT NULL,
--   NAME            VARCHAR(200),
--
--   PRIMARY KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID),
--   FOREIGN KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID) REFERENCES MAMA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID)
-- );
--
-- CREATE TABLE BEAR_TOY
-- (
--   BEAR_CONTEXT_ID INT NOT NULL,
--   PAPA_BEAR_ID    INT NOT NULL,
--   MAMA_BEAR_ID    INT NOT NULL,
--   BABY_BEAR_ID    INT NOT NULL,
--   BEAR_TOY_ID     INT NOT NULL,
--   NAME            VARCHAR(200),
--
--   PRIMARY KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID, BEAR_TOY_ID),
--   FOREIGN KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID) REFERENCES BABY_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID)
-- );
--
-- CREATE TABLE DEER_FRIEND
-- (
--   DEER_ID         INT NOT NULL,
--   BEAR_CONTEXT_ID INT NOT NULL,
--   PAPA_BEAR_ID    INT NOT NULL,
--   MAMA_BEAR_ID    INT NOT NULL,
--   BABY_BEAR_ID    INT NOT NULL,
--
--   PRIMARY KEY (DEER_ID),
--   FOREIGN KEY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID) REFERENCES BABY_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID)
-- );


-- Test Data Setup
insert into BEAR_CONTEXT (BEAR_CONTEXT_ID) values (1);

insert into PAPA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, NAME) values (1,1,'Prime Bear');
insert into PAPA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, NAME) values (1,2,'Scar');

insert into MAMA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, NAME) values (1,1,1,'Good Mama');
insert into MAMA_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, NAME) values (1,1,2,'Not used');

insert into BABY_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID, NAME) values (1,1,1,1,'B1');
insert into BABY_BEAR (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID, NAME) values (1,1,1,2,'B2');

insert into BEAR_TOY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID, BEAR_TOY_ID, NAME) values (1,1,1,1,1,'PS4');
insert into BEAR_TOY (BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID, BEAR_TOY_ID, NAME) values (1,1,1,1,2,'WII');

insert into DEER_FRIEND (DEER_ID, BEAR_CONTEXT_ID, PAPA_BEAR_ID, MAMA_BEAR_ID, BABY_BEAR_ID) values (1,1,1,1,1);

COMMIT;